---
title: "Untitled"
author: "Neznani partizan"
date: "03 marec 2016"
output: html_document
---

```{r setup_packages}
library(knitr)
library(DT)
library(htmltools)
library(htmlTable)
devtools::load_all()
```

```{r prepare_data}
xy <- readColony(proj = "d:/colony/volkovi", comp = "LC")
off <- readColony(proj = "d:/colony/volkovi/", comp = "offspring_genotype")

locnames <- unique(sub("\\.1$|\\.2$", "", names(off)[-which(names(off) == "sample.name")]))

off <- as.data.frame(cbind(sample.name = as.character(off[, 1]), sapply(locnames, FUN = function(x, df) {
  apply(df[, grepl(pattern = x, x = colnames(df))], MARGIN = 1, FUN = function(m) paste(m, collapse = "/"))
}, df = off)))

out <- merge(xy, off, sort = FALSE)
```

```{r test_preview, echo = FALSE, eval = FALSE}
sort(table(out$clone.index))

out[out$clone.index %in% 1, ]
out[out$clone.index %in% 2, ]
out[out$clone.index %in% 4, ]
out[out$clone.index %in% 10, ]
out[out$clone.index %in% 158, ]

```

From Wang (2016) on likelihood clustering method (LC) on probability: Each partition is evaluated for its likelihood which is equal to the probability of the genotype data given the partition, and the one with the maximum like-lihood is returned as the best estimate.

# htmlTable solution
```{r htmlTable_showcase}
grp <- table(out$clone.index)
htmlTable(out, rgroup = paste("Individual", 1:length(grp)),
          n.rgroup = grp,
          col.rgroup = c("none", "#999966"))
```

# Datatables solution
```{r DT_showcase, results = "asis", eval = FALSE, echo = FALSE}
# htmltools::tagList(
#   lapply(split(out, out$clone.index), datatable))
```

# All data in one tables (searchable)
```{r datatables_all_in_one}
formatStyle(datatable(out, style = "default", extensions = "FixedHeader"),
            columns = seq(from = 4, to = ncol(out), by = 2),
              backgroundColor = "grey")
```